language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --dev

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
